// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_PROJECT_ID =
  import.meta.env.VITE_SUPABASE_PROJECT_ID ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_PROJECT_ID ||
  import.meta.env.SUPABASE_PROJECT_ID;
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_URL ||
  import.meta.env.SUPABASE_URL ||
  (SUPABASE_PROJECT_ID ? `https://${SUPABASE_PROJECT_ID}.supabase.co` : undefined);
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.SUPABASE_ANON_KEY;

const FALLBACK_SUPABASE_URL = 'https://invalid.localhost';
const FALLBACK_SUPABASE_KEY = 'missing-supabase-key';
const SUPABASE_MISSING_CONFIG_MESSAGE =
  'Supabase is not configured. Set VITE_SUPABASE_URL (or VITE/NEXT_PUBLIC/SUPABASE project id) and a publishable/anon key in deployment environment variables.';

const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  if (import.meta.env.DEV) {
    console.warn(SUPABASE_MISSING_CONFIG_MESSAGE);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || FALLBACK_SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_KEY,
  {
    global: {
      // Prevent noisy network failures when config is missing.
      fetch: isSupabaseConfigured
        ? fetch
        : async () =>
            new Response(
              JSON.stringify({
                code: 'SUPABASE_NOT_CONFIGURED',
                message: SUPABASE_MISSING_CONFIG_MESSAGE,
                details: '',
                hint: '',
              }),
              {
                status: 503,
                headers: { 'Content-Type': 'application/json' },
              }
            ),
    },
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);